# KENSHI (PRIMARY)
spring.datasource.kenshi.jdbc-url=jdbc:mysql://localhost:3306/kenshi
spring.datasource.kenshi.username=root
spring.datasource.kenshi.password=password
spring.datasource.kenshi.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.rss.jdbc-url=jdbc:mysql://localhost:3306/rss
spring.datasource.rss.username=root
spring.datasource.rss.password=password
spring.datasource.rss.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA GLOBAL (optionnel mais OK)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect